test:
	go test -coverprofile=coverage.out ./...       
	go tool cover -html=coverage.out -o coverage.html
	go test ./...

// mockgen -source=internal/services/user.go -destination=internal/services/mocks/user_mock.go -package=mocks